### ISSUE TITLE
ApiError: status_code: 401

### ISSUE THREAD

**Issue by Mzakery** [Nixtla/nixtla#189] opened 2023-12-08 21:03 UTC
Hello
I also got the 401 error.
I registered on the site and received the token, but unfortunately I still get the 401 error.
please guide me

ApiError: status_code: 401, body: {'data': None, 'message': 'Invalid API key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'E7F2BBTB2P', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

**Comment by AzulGarza** [comment] 2023-12-09 07:33
hi @Mzakery. thanks for using nixtla. could you provide an example or screenshot of how you call the sdk?

**Comment by Mzakery** [comment] 2023-12-09 12:42
I registered on the website https://www.nixtla.io/ and received the token from the Get token section and defined it as a environment variable.
I want to run the codes of this section

https://github.com/Nixtla/nixtla/blob/main/nbs/docs/getting-started/1_getting_started_short.ipynb

  that in part
timegpt.validate_token()
And
timegpt_fcst_df = timegpt.forecast(df=df, h=12, freq='MS', time_col='timestamp', target_col='value')
timegpt_fcst_df.head()
  
It gives error 401

ApiError: status_code: 401, body: { 'data': None, 'message': 'Invalid API Key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'E7F2BBTB2P' , 'support': 'If you have any questions or need support, please email ops@nixtla.io'}

**Comment by Mzakery** [comment] 2023-12-09 12:49
Codes run in colab with version 3.10

**Comment by Mzakery** [comment] 2023-12-10 11:42
load_dotenv('c.env')
True
TIMEGPT_TOKEN=os.environ.get("TIMEGPT_TOKEN")
TIMEGPT_TOKEN
'... token...'
timegpt = TimeGPT(
    # defaults to os.environ.get("TIMEGPT_TOKEN")
    token = 'TIMEGPT_TOKEN')
timegpt.validate_token()

ApiError                                  Traceback (most recent call last)
[<ipython-input-39-3be6d60ea913>](https://localhost:8080/#) in <cell line: 1>()
----> 1 timegpt.validate_token()

1 frames
[/usr/local/lib/python3.10/dist-packages/nixtlats/timegpt.py](https://localhost:8080/#) in validate_token(self, log)
    725     def validate_token(self, log: bool = True) -> bool:
    726         """Returns True if your token is valid."""
--> 727         validation = self.client.validate_token()
    728         valid = False
    729         if "message" in validation:

[/usr/local/lib/python3.10/dist-packages/nixtlats/client.py](https://localhost:8080/#) in validate_token(self)
    419         except JSONDecodeError:
    420             raise ApiError(status_code=_response.status_code, body=_response.text)
--> 421         raise ApiError(status_code=_response.status_code, body=_response_json)
    422 
    423     def validate_token_front(self) -> typing.Any:

ApiError: status_code: 401, body: {'data': None, 'message': 'Invalid API key', 'details': 'Key not found', 'code': 'A12', 'requestID': 'RQVKJPWP2N', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

**Comment by AzulGarza** [comment] 2023-12-11 21:27
hey @Mzakery! 

Thanks for using TimeGPT.

I think the problem is related to this line:

```python
timegpt = TimeGPT(
# defaults to os.environ.get("TIMEGPT_TOKEN")
token = 'TIMEGPT_TOKEN')
```

There, you're passing the string `'TIMEGPT_TOKEN'` as a token. Instead, since you're loading your env variables, just `timegpt = TimeGPT()` should work. Alternatively, simply removing the quotes to access the `TIMEGPT_TOKEN` object should work as well,

```python
timegpt = TimeGPT(token=TIMEGPT_TOKEN)
```

**Comment by Mzakery** [comment] 2023-12-12 07:29
Thanks
But it gives error 429 in this part.

timegpt.validate_token()

ApiError                                  Traceback (most recent call last)
[<ipython-input-40-3be6d60ea913>](https://localhost:8080/#) in <cell line: 1>()
----> 1 timegpt.validate_token()

1 frames
[/usr/local/lib/python3.10/dist-packages/nixtlats/client.py](https://localhost:8080/#) in validate_token(self)
    419         except JSONDecodeError:
    420             raise ApiError(status_code=_response.status_code, body=_response.text)
--> 421         raise ApiError(status_code=_response.status_code, body=_response_json)
    422 
    423     def validate_token_front(self) -> typing.Any:

ApiError: status_code: 429, body: {'data': None, 'message': 'Too many requests', 'details': 'You have reached your request limit, email [ops@nixtla.io](mailto:ops@nixtla.io) to continue using the API', 'code': 'A20', 'requestID': '868HB5JZ5T', 'support': 'If you have questions or need support, please email [ops@nixtla.io](mailto:ops@nixtla.io)'}

**Comment by elephaint** [comment] 2024-07-30 20:03
@Mzakery I suspect this issue is no longer relevant, no?

**Comment by mergenthaler** [comment] 2024-08-06 18:29
Closing this, but feel free to re-open if necessary.

**Closed by mergenthaler** 2024-08-06 18:29 UTC
